vich_uploader:
    db_driver: orm

    metadata:
       type: attribute
       
    mappings:
       image_produit:
           uri_prefix: /image/produit
           upload_destination: '%kernel.project_dir%/public/image/produit'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
       image_prestation:
           uri_prefix: /image/prestation
           upload_destination: '%kernel.project_dir%/public/image/prestation'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       image_logo:
           uri_prefix: /image/logo
           upload_destination: '%kernel.project_dir%/public/image/logo'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
